# Generated by Django 5.0 on 2023-12-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                
                ('id', models.FloatField(primary_key=True,default=1)),
                ('nombre', models.CharField(default='IA en mantenimiento', max_length=200)),
                ('link', models.CharField(default='IA en mantenimiento', max_length=800)),
                ('imagen', models.CharField(default='IA en mantenimiento', max_length=200)),
                
            ],
            options={
                'db_table': 'ias',
            },
        ),
    ]
