# Generated by Django 5.0 on 2023-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='funcion_imagen',
        ),
        migrations.RemoveField(
            model_name='store',
            name='funcion_nombre',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ias_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ias_imagen',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ias_link',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ias_nombre',
        ),
        migrations.RemoveField(
            model_name='store',
            name='relacion_id',
        ),
        migrations.AddField(
            model_name='store',
            name='imagen',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='link',
            field=models.CharField(default='...', max_length=800),
        ),
        migrations.AddField(
            model_name='store',
            name='nombre',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.FloatField(default=1, primary_key=True, serialize=False),
        ),
    ]
